Feature/movie list
kFocusing/Movies pull request #1
Opened 2022-05-02 00:32 UTC by kFocusing

2022-05-03 20:33 UTC, Nikitaix2311 requested changes
в целом - всё ок. кое-что нужно поправить. и есть моменты для обсуждения.

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/BaseComponents/BaseViewController.swift
> +    func configureErrorAlert(with error: String?) {
configureErrorAlert(with error: String?) => `showErrorAlert(with message: String)`

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/Extensions/UILabelExtension.swift
> +                    shadowColor: UIColor = .black) {
а другие параметры тени? прозрачность, радиус , корнер радиус и тд

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/Extensions/UIViewExtension.swift
> +    func makeRoundCorner(_ rounding: Int) {
rounding
неинформативное название параметра

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        if itemsCount() != 0 {
itemsCount() != 0 => `dataSource.isNotEmpty`

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +    func pagination() {
метод не называется существительным. в названии метода должно быть действие. например "loadMore"/"fetchMore"

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        isPagination = true
isPagination название неинформативное

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        currentPage += 1
разве в этой апи нет в пагинации параметра linit?

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +    private func getSearchMovies() {
getSearchMovies

так get movies или search movies?

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        if itemsCount() != 0 {
the same here

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/MoviePreviewCell/MoviePreviewXibTableViewCell.swift
> +    @IBOutlet weak var titleLabel: UILabel!
outlet-ы должны быть приватными

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +    private func showSortAlert() {
showSortAlert
это не совсем алерт

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +            self.presenter.sortPosts(by: .defaultSort)
плохо с чекмарком. погугли как еще его можно сделать) не текстом) 
это костылище . его можно добавлять программно.

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +        if indexPath.row == (presenter.itemsCount() - 3)
(presenter.itemsCount() - 3) => можно назвать это как-то. чтоб было понятно, что за магическое число

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +            && (presenter.itemsCount() == presenter.getCurrentPage() * 20) {
что-то тут непонятные условия. давай созвонимся по этому поводу

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +        self.tableView.tableFooterView = createFooterSpinner()
не вижу проверку условия на isLoading. ни тут, ни в презентере

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +    func scrollToTop() {
можно вынести в экстеншн таблицы

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +        if presenter.itemsCount() != 0 {
isNotEmpty

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/NetworkService/Endpoint.swift
> +    static let baseURL = "https://api.themoviedb.org/3/"
можно и так, но лучше с енвайронметом делать. закладывая наперёд, что может у приложения быть не один сервер

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/NetworkService/Endpoint.swift
> +        case .list,
если все геты, то можно не указывать кейсы и написать default: .get

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/NetworkService/Endpoint.swift
> +             .genres,
то же самое

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/NetworkService/Endpoint.swift
> +enum SortType: Int, CaseIterable {
что здесь делает сорт?

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/NetworkService/GenerService.swift
> +    func getGenres(by id: [Int]) -> [GenreModel] {
а по айдишнику чего мы ищем?

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/NetworkService/GenerService.swift
> +        for id in id {
for id in id
 
 не называй одинаково эти разные параметры

2022-05-03 20:33 UTC, Nikitaix2311 commented on Movies/NetworkService/NetworkService.swift
> +    static let shared = NetworkService()
можно и синглтоном оставить. ну раз уже через Assembly собираешь, то можно было бы там, конечно, и заинитить зависимость новую (новый инстанс сервиса). 
не заморачивайся над этим , в принципе. но такой момент есть

2022-05-04 14:45 UTC, kFocusing commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        isPagination = true
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +    private func getSearchMovies() {
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/BaseComponents/BaseViewController.swift
> +    func configureErrorAlert(with error: String?) {
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/Extensions/UILabelExtension.swift
> +                    shadowColor: UIColor = .black) {
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        if itemsCount() != 0 {
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +    func pagination() {
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        if itemsCount() != 0 {
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/View/MoviePreviewCell/MoviePreviewXibTableViewCell.swift
> +    @IBOutlet weak var titleLabel: UILabel!
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +    private func showSortAlert() {
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +            self.presenter.sortPosts(by: .defaultSort)
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +        if indexPath.row == (presenter.itemsCount() - 3)
solved

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +            && (presenter.itemsCount() == presenter.getCurrentPage() * 20) {
call

2022-05-04 16:52 UTC, kFocusing commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +        self.tableView.tableFooterView = createFooterSpinner()
solved

2022-05-04 16:53 UTC, kFocusing commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +    func scrollToTop() {
solved

2022-05-04 16:53 UTC, kFocusing commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +        if presenter.itemsCount() != 0 {
solved

2022-05-04 16:53 UTC, kFocusing commented on Movies/NetworkService/Endpoint.swift
> +    static let baseURL = "https://api.themoviedb.org/3/"
solved

2022-05-04 16:53 UTC, kFocusing commented on Movies/NetworkService/Endpoint.swift
> +        case .list,
solved

2022-05-04 16:53 UTC, kFocusing commented on Movies/NetworkService/Endpoint.swift
> +enum SortType: Int, CaseIterable {
solved

2022-05-04 16:53 UTC, kFocusing commented on Movies/NetworkService/GenerService.swift
> +        for id in id {
solved

2022-05-04 16:53 UTC, kFocusing commented on Movies/NetworkService/NetworkService.swift
> +    static let shared = NetworkService()
solved

2022-05-05 09:35 UTC, Nikitaix2311 requested changes
еще немножко

2022-05-05 09:35 UTC, Nikitaix2311 commented on Movies/Extensions/UITableViewExntension.swift
> +                                                     section: 0),
табуляция поехала. поправишь плз

2022-05-05 09:35 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        return !dataSource.isEmpty
нет. я имел ввиду сделать екстеншн для массивов. 

у которого будет свойство isNotEmpty: Bool. и к нему везде обращаться

2022-05-05 09:35 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        return isLoading
необязательно было создавать метод. это свойство может быть приватным, и ты можешь проверять это условие прямо в методе пагинации в презентере. если сейчас не выполняется запрос, то проходим дальше. вот и всё

2022-05-05 09:35 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +        actionSheet.actions.indices.forEach {
self.presenter.selectedSortType()
                                             == SortType.allCases[$0] ? true
                                             : false
                                             
тернарный оператор здесь излишний. 

`self.presenter.selectedSortType()
                                             == SortType.allCases[$0]` уже возвращает булевое значение)

2022-05-05 09:35 UTC, Nikitaix2311 commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +            && presenter.getCurrentPage() < presenter.getTotalPages() {
вообще была идея не со страницами, а с результатами) количеством результатов)

2022-05-05 09:35 UTC, Nikitaix2311 commented on Movies/NetworkService/Endpoint.swift
> +    func fullURLString() -> String {
просил сделать метод статическим, принимающим endpoint или path

2022-05-05 10:11 UTC, kFocusing commented on Movies/Extensions/UITableViewExntension.swift
> +                                                     section: 0),
solved

2022-05-05 10:11 UTC, kFocusing commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        return !dataSource.isEmpty
исправил, но метод мне всё равно нужен ибо использую его в контролере, где нет доступа к датаСорсу

2022-05-05 10:14 UTC, kFocusing commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +        actionSheet.actions.indices.forEach {
solved

2022-05-05 10:18 UTC, kFocusing commented on Movies/MovieListModule/View/View/MovieListViewController.swift
> +            && presenter.getCurrentPage() < presenter.getTotalPages() {
solved

2022-05-05 10:24 UTC, kFocusing commented on Movies/NetworkService/Endpoint.swift
> +    func fullURLString() -> String {
solved

2022-05-05 10:49 UTC, kFocusing commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        return isLoading
solved

2022-05-06 17:42 UTC, Nikitaix2311 requested changes
пара комментов еще

2022-05-06 17:42 UTC, Nikitaix2311 commented on Movies/Extensions/ArrayExtension.swift
> +    var isNonEmpty: Bool  {
is NOT empty!

2022-05-06 17:42 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        return !dataSource.isEmpty
не вижу, чтоб здесь вызывалось dataSource.isNotEmpty

2022-05-06 17:42 UTC, Nikitaix2311 commented on Movies/MovieListModule/Presenter/MovieListPresenter.swift
> +        return isLoading
метод нигде не используется. его следует удалить

2022-05-06 17:42 UTC, Nikitaix2311 commented on Movies/NetworkService/NetworkService.swift
> +    static let shared = NetworkService()
вообще , сомнительное сочетание. 
синглтон является реализацией протокола.
давай или уберем синглтон , или протокол

2022-05-09 11:01 UTC, merged